from .add_transform import AddTransform
from .select import Select
from .adjust_alpha import AdjustAlpha
from .autocrop import Autocrop
from .scale import Scale
from .crop import Crop
from .grab import Grab
from .duplicate import Duplicate
from .rotate import Rotate
from .call_menu import CallMenu
from .call_menu import MenuInsertKeyframe
from .call_menu import InsertKeyframe
from .delete import Delete
from .meta_toggle import MetaToggle
from .set_cursor2d import SetCursor2d
